"""Add user_id to Checklist

Revision ID: 1462907f5829
Revises: c2860b8fd00b
Create Date: 2025-09-17 01:10:49.204426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1462907f5829'
down_revision = 'c2860b8fd00b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_checklists_user_id',   # ✅ explicit name
            'users',
            ['user_id'],
            ['id']
        )
        batch_op.drop_column('date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_constraint('fk_checklists_user_id', type_='foreignkey')  # ✅ same name
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
